// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audit_action_from_u8`, `bytes_to_array_ffi`, `clear_progress`, `register_cancel_flag`, `register_progress`, `share_role_from_u8`

/// Generate a new RSA-2048 keypair.
/// Returns (private_key_pem, public_key_pem, fingerprint).
RsaKeyPair generateRsaKeypair() =>
    RustLib.instance.api.crateApiGenerateRsaKeypair();

/// Derive the public key PEM and fingerprint from a private key PEM.
RsaPublicInfo rsaPublicFromPrivate({required String privateKeyPem}) => RustLib
    .instance
    .api
    .crateApiRsaPublicFromPrivate(privateKeyPem: privateKeyPem);

/// Sign a message with an RSA private key (PSS + SHA256).
/// Returns the signature as a base64 string.
String rsaSign({required String message, required String privateKeyPem}) =>
    RustLib.instance.api.crateApiRsaSign(
      message: message,
      privateKeyPem: privateKeyPem,
    );

/// Verify an RSA signature (PSS + SHA256).
bool rsaVerify({
  required String message,
  required String signature,
  required String publicKeyPem,
}) => RustLib.instance.api.crateApiRsaVerify(
  message: message,
  signature: signature,
  publicKeyPem: publicKeyPem,
);

/// Encrypt a plaintext string with an RSA public key (PKCS#1 v1.5).
/// Returns the ciphertext as a base64 string.
String rsaEncrypt({required String plaintext, required String publicKeyPem}) =>
    RustLib.instance.api.crateApiRsaEncrypt(
      plaintext: plaintext,
      publicKeyPem: publicKeyPem,
    );

/// Decrypt a base64-encoded ciphertext with an RSA private key (PKCS#1 v1.5).
/// Returns the plaintext as a UTF-8 string.
String rsaDecrypt({
  required String ciphertextB64,
  required String privateKeyPem,
}) => RustLib.instance.api.crateApiRsaDecrypt(
  ciphertextB64: ciphertextB64,
  privateKeyPem: privateKeyPem,
);

/// Generate a new hybrid wrapping keypair.
/// Returns the private and public key PEM containers.
WrappingKeyPair generateWrappingKeypair() =>
    RustLib.instance.api.crateApiGenerateWrappingKeypair();

/// Wrap a file key to a recipient's hybrid wrapping public key.
/// Returns the wrap blob as a base64 string.
String wrappingWrap({
  required List<int> fileKey,
  required String recipientPublicPem,
}) => RustLib.instance.api.crateApiWrappingWrap(
  fileKey: fileKey,
  recipientPublicPem: recipientPublicPem,
);

/// Unwrap a base64 hybrid wrap blob with the recipient's wrapping private key.
/// Returns the file key bytes.
Uint8List wrappingUnwrap({required String blob, required String privatePem}) =>
    RustLib.instance.api.crateApiWrappingUnwrap(
      blob: blob,
      privatePem: privatePem,
    );

/// Generate a new Ed25519 keypair.
/// Returns (private_pem PKCS#8, public_pem SPKI).
Ed25519KeyPair generateEd25519Keypair() =>
    RustLib.instance.api.crateApiGenerateEd25519Keypair();

/// Sign a message with an Ed25519 private key.
/// Returns the signature as a base64 string.
String ed25519Sign({required String message, required String privatePem}) =>
    RustLib.instance.api.crateApiEd25519Sign(
      message: message,
      privatePem: privatePem,
    );

/// Sign raw bytes with an Ed25519 private key.
/// Returns the signature as a base64 string.
String ed25519SignBytes({
  required List<int> message,
  required String privatePem,
}) => RustLib.instance.api.crateApiEd25519SignBytes(
  message: message,
  privatePem: privatePem,
);

/// Verify an Ed25519 signature.
bool ed25519Verify({
  required String message,
  required String signature,
  required String publicPem,
}) => RustLib.instance.api.crateApiEd25519Verify(
  message: message,
  signature: signature,
  publicPem: publicPem,
);

/// Verify an Ed25519 signature over raw bytes.
bool ed25519VerifyBytes({
  required List<int> message,
  required String signature,
  required String publicPem,
}) => RustLib.instance.api.crateApiEd25519VerifyBytes(
  message: message,
  signature: signature,
  publicPem: publicPem,
);

/// SHA-256 fingerprint of a SPKI public key PEM, as 64 hex chars — the
/// Curve25519 counterpart to [rsa_fingerprint_public].
String spkiFingerprint({required String publicPem}) =>
    RustLib.instance.api.crateApiSpkiFingerprint(publicPem: publicPem);

/// Generate a random symmetric key for the given cipher.
/// Cipher: "aegis128l" (default), "ascon128a", "chacha20poly1305", "aegis256"
Uint8List cipherGenerateKey({required String cipher}) =>
    RustLib.instance.api.crateApiCipherGenerateKey(cipher: cipher);

/// Encrypt plaintext bytes with a symmetric cipher.
Uint8List cipherEncrypt({
  required String cipher,
  required List<int> key,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiCipherEncrypt(
  cipher: cipher,
  key: key,
  plaintext: plaintext,
);

/// Decrypt ciphertext bytes with a symmetric cipher.
Uint8List cipherDecrypt({
  required String cipher,
  required List<int> key,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiCipherDecrypt(
  cipher: cipher,
  key: key,
  ciphertext: ciphertext,
);

/// Encrypt a metadata string (file name, thumbnail, link fields) with a
/// fresh random nonce prepended to the ciphertext. Metadata strings share
/// the file key with the content chunks, so encrypting them with the key
/// blob as-is would reuse the embedded nonce.
Uint8List cipherEncryptString({
  required String cipher,
  required List<int> key,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiCipherEncryptString(
  cipher: cipher,
  key: key,
  plaintext: plaintext,
);

/// Decrypt a metadata string. Tries the prepended random nonce first, then
/// falls back to the legacy embedded-nonce layout so metadata written before
/// per-string nonces still decrypts — the AEAD tag rejects the wrong branch.
Uint8List cipherDecryptString({
  required String cipher,
  required List<int> key,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiCipherDecryptString(
  cipher: cipher,
  key: key,
  ciphertext: ciphertext,
);

/// Encrypt one chunk of a multi-chunk payload with a per-chunk derived nonce.
/// Chunk 0 is byte-identical to [cipher_encrypt], so single-chunk payloads
/// stay wire-compatible with every existing file.
Uint8List cipherEncryptChunk({
  required String cipher,
  required List<int> key,
  required BigInt chunkIndex,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiCipherEncryptChunk(
  cipher: cipher,
  key: key,
  chunkIndex: chunkIndex,
  plaintext: plaintext,
);

/// Decrypt one chunk of a multi-chunk payload. Tries the per-chunk nonce
/// first, then falls back to the blob's own nonce so files uploaded before
/// per-chunk nonces existed still decrypt — the AEAD tag rejects the wrong
/// branch.
Uint8List cipherDecryptChunk({
  required String cipher,
  required List<int> key,
  required BigInt chunkIndex,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiCipherDecryptChunk(
  cipher: cipher,
  key: key,
  chunkIndex: chunkIndex,
  ciphertext: ciphertext,
);

/// Compute SHA-256 hash of the input bytes. Returns hex string.
String sha256Digest({required List<int> data}) =>
    RustLib.instance.api.crateApiSha256Digest(data: data);

/// Compute CRC-16 checksum. Returns hex string.
String crc16Digest({required List<int> data}) =>
    RustLib.instance.api.crateApiCrc16Digest(data: data);

/// Derive the account-wide search key from a private key PEM. Hex-encoded so
/// it can be held alongside the other client-side key material.
String searchRootKey({required String privateKeyPem}) =>
    RustLib.instance.api.crateApiSearchRootKey(privateKeyPem: privateKeyPem);

/// Derive a file's search key from the key its contents are encrypted with.
String searchFileKey({required List<int> fileKey}) =>
    RustLib.instance.api.crateApiSearchFileKey(fileKey: fileKey);

/// Tag one value: a file name for `name_hash`, or a single query word.
String searchTag({required String keyHex, required String value}) =>
    RustLib.instance.api.crateApiSearchTag(keyHex: keyHex, value: value);

/// Tokenize and tag text. Format: "tag:weight;tag:weight;..."
String searchTagTokens({required String keyHex, required String text}) =>
    RustLib.instance.api.crateApiSearchTagTokens(keyHex: keyHex, text: text);

/// Base64 encode bytes.
String base64Encode({required List<int> data}) =>
    RustLib.instance.api.crateApiBase64Encode(data: data);

/// Base64 decode a string to bytes.
Uint8List base64Decode({required String data}) =>
    RustLib.instance.api.crateApiBase64Decode(data: data);

/// DER-encode a v1 share-request payload. Byte-for-byte equivalent to the
/// WASM `share_payload_encode_v1`; both call `cryptfns::asn1` directly.
Uint8List sharePayloadEncodeV1({
  required List<int> senderId,
  required List<int> recipientId,
  required List<int> recipientPubkeyFingerprint,
  required int shareRole,
  required List<int> rootFileId,
  required List<int> entriesHash,
  required PlatformInt64 timestamp,
  required List<int> nonce,
}) => RustLib.instance.api.crateApiSharePayloadEncodeV1(
  senderId: senderId,
  recipientId: recipientId,
  recipientPubkeyFingerprint: recipientPubkeyFingerprint,
  shareRole: shareRole,
  rootFileId: rootFileId,
  entriesHash: entriesHash,
  timestamp: timestamp,
  nonce: nonce,
);

/// DER-encode a v1 folder member-signature payload.
Uint8List memberSigEncodeV1({
  required List<int> userId,
  required List<int> pubkeyDer,
  required List<int> fingerprint,
  required int shareRole,
  required PlatformInt64 signedAt,
}) => RustLib.instance.api.crateApiMemberSigEncodeV1(
  userId: userId,
  pubkeyDer: pubkeyDer,
  fingerprint: fingerprint,
  shareRole: shareRole,
  signedAt: signedAt,
);

/// DER-encode a v1 folder member list. Byte-for-byte equivalent to the
/// WASM `folder_member_list_encode_v1`. Members travel as flat parallel
/// arrays so the FFI surface stays a single sync call: `user_ids` and
/// `signed_by_user_ids` concatenate every 16-byte UUID, `pubkey_finger-
/// prints` concatenates every 32-byte SHA-256, and `share_roles` /
/// `is_owner_flags` carry one byte per member. The encoder sorts by
/// `user_id` so callers can pass members in any order.
Uint8List folderMemberListEncodeV1({
  required List<int> folderId,
  required List<int> folderOwnerId,
  required List<int> userIds,
  required List<int> pubkeyFingerprints,
  required List<int> shareRoles,
  required List<int> isOwnerFlags,
  required List<int> signedByUserIds,
  required PlatformInt64 membersSignedAt,
}) => RustLib.instance.api.crateApiFolderMemberListEncodeV1(
  folderId: folderId,
  folderOwnerId: folderOwnerId,
  userIds: userIds,
  pubkeyFingerprints: pubkeyFingerprints,
  shareRoles: shareRoles,
  isOwnerFlags: isOwnerFlags,
  signedByUserIds: signedByUserIds,
  membersSignedAt: membersSignedAt,
);

/// DER-encode a v1 audit-event row body. Pass `share_role = 255` for
/// events that don't carry a role (e.g. `revoke`).
Uint8List auditEventEncodeV1({
  required List<int> senderId,
  required List<int> recipientId,
  required List<int> fileId,
  required String action,
  required int shareRole,
  required PlatformInt64 createdAt,
}) => RustLib.instance.api.crateApiAuditEventEncodeV1(
  senderId: senderId,
  recipientId: recipientId,
  fileId: fileId,
  action: action,
  shareRole: shareRole,
  createdAt: createdAt,
);

/// DER-encode a v1 audit-event signature input. `recipient_id` is absent
/// when the caller passes an empty `Vec` (255 is a legal UUID byte, so an
/// empty buffer is the sentinel); each role field uses byte `255` for an
/// absent role.
Uint8List auditEventSigInputEncodeV1({
  required List<int> senderId,
  required List<int> recipientId,
  required List<int> fileId,
  required int action,
  required int shareRoleBefore,
  required int shareRoleAfter,
  required PlatformInt64 timestamp,
}) => RustLib.instance.api.crateApiAuditEventSigInputEncodeV1(
  senderId: senderId,
  recipientId: recipientId,
  fileId: fileId,
  action: action,
  shareRoleBefore: shareRoleBefore,
  shareRoleAfter: shareRoleAfter,
  timestamp: timestamp,
);

/// DER-encode the canonical entries list that `entries_hash` commits to.
/// `file_ids` concatenates every 16-byte file UUID, `encrypted_keys_flat`
/// concatenates every per-entry ciphertext, and `encrypted_key_lengths`
/// carries each ciphertext length so the flat buffer can be sliced. The
/// encoder sorts by `file_id`, so the hash is stable under input ordering.
Uint8List entriesEncodeV1({
  required List<int> fileIds,
  required List<int> encryptedKeysFlat,
  required List<int> encryptedKeyLengths,
}) => RustLib.instance.api.crateApiEntriesEncodeV1(
  fileIds: fileIds,
  encryptedKeysFlat: encryptedKeysFlat,
  encryptedKeyLengths: encryptedKeyLengths,
);

/// Sign raw bytes (RSA-PSS-SHA256) with a PEM private key. Sharing payloads
/// are DER blobs that aren't valid UTF-8, so they can't go through the
/// string-typed `rsa_sign`. Returns a base64 signature.
String rsaSignBytes({
  required List<int> message,
  required String privateKeyPem,
}) => RustLib.instance.api.crateApiRsaSignBytes(
  message: message,
  privateKeyPem: privateKeyPem,
);

/// Verify an RSA-PSS-SHA256 signature over raw bytes with a PEM public key.
bool rsaVerifyBytes({
  required List<int> message,
  required String signature,
  required String publicKeyPem,
}) => RustLib.instance.api.crateApiRsaVerifyBytes(
  message: message,
  signature: signature,
  publicKeyPem: publicKeyPem,
);

/// SHA-256 fingerprint (`sha256(hex(modulus))`) of a PEM public key — the
/// same value the server stores in `users.fingerprint`, derived client-side
/// for TOFU verification of a recipient before sharing.
String rsaFingerprintPublic({required String publicKeyPem}) => RustLib
    .instance
    .api
    .crateApiRsaFingerprintPublic(publicKeyPem: publicKeyPem);

/// PKCS#1 DER bytes of a PEM public key — the `pubkey_der` octet string the
/// `member_sig` encoder commits to. The byte conversion lives in `cryptfns`
/// so web and mobile produce identical member signatures.
Uint8List rsaPkcs1DerFromPem({required String publicKeyPem}) =>
    RustLib.instance.api.crateApiRsaPkcs1DerFromPem(publicKeyPem: publicKeyPem);

/// The `MemberSigPayloadV1.pubkey_der` canonical for a recipient of the given
/// key type: PKCS#1 DER body for `"rsa"`, SPKI DER body for `"curve25519"`.
/// The dispatch lives in `cryptfns` so web and mobile commit to identical
/// bytes.
Uint8List memberPubkeyDer({
  required String keyType,
  required String publicKeyPem,
}) => RustLib.instance.api.crateApiMemberPubkeyDer(
  keyType: keyType,
  publicKeyPem: publicKeyPem,
);

/// Begin an OPAQUE registration. Returns the opaque client state to carry
/// forward and the base64 message to POST to the server's `registration/start`.
OpaqueClientStart opaqueClientRegistrationStart({
  required List<int> password,
}) => RustLib.instance.api.crateApiOpaqueClientRegistrationStart(
  password: password,
);

/// Finish an OPAQUE registration against the server's `registration_response`.
/// Returns the base64 message to POST and the export key used to seal the
/// user's key bundle.
///
/// A registration always seals under the current default KSF, read straight
/// from the shared crate so a work-factor change stays in lockstep with what the
/// server records for the account.
OpaqueRegisterFinish opaqueClientRegistrationFinish({
  required String registrationState,
  required String registrationResponse,
  required List<int> password,
}) => RustLib.instance.api.crateApiOpaqueClientRegistrationFinish(
  registrationState: registrationState,
  registrationResponse: registrationResponse,
  password: password,
);

/// Begin an OPAQUE login. Returns the opaque client state and the base64
/// message to POST to the server's `login/start`.
OpaqueClientStart opaqueClientLoginStart({required List<int> password}) =>
    RustLib.instance.api.crateApiOpaqueClientLoginStart(password: password);

/// Finish an OPAQUE login against the server's `credential_response`. Returns
/// the finalization message, the shared session key, and the export key that
/// unseals the user's key bundle.
///
/// The KSF parameters are the account's own, echoed by `login/start`. The
/// `export_key` only matches what registration produced when it is stretched
/// with those same parameters, so a future work-factor raise cannot lock the
/// account out.
OpaqueLoginFinish opaqueClientLoginFinish({
  required String loginState,
  required String credentialResponse,
  required List<int> password,
  required int mCost,
  required int tCost,
  required int pCost,
}) => RustLib.instance.api.crateApiOpaqueClientLoginFinish(
  loginState: loginState,
  credentialResponse: credentialResponse,
  password: password,
  mCost: mCost,
  tCost: tCost,
  pCost: pCost,
);

/// Derive the 32-byte key-encryption key from an OPAQUE export key.
Uint8List envelopeDeriveKek({required List<int> exportKey}) =>
    RustLib.instance.api.crateApiEnvelopeDeriveKek(exportKey: exportKey);

/// Seal a key bundle under a KEK. Returns the base64 envelope.
String envelopeSeal({required List<int> kek, required List<int> bundle}) =>
    RustLib.instance.api.crateApiEnvelopeSeal(kek: kek, bundle: bundle);

/// Open a base64 envelope with a KEK. Returns the plaintext key bundle.
Uint8List envelopeOpen({required List<int> kek, required String envelope}) =>
    RustLib.instance.api.crateApiEnvelopeOpen(kek: kek, envelope: envelope);

/// Re-seal an envelope under a new KEK without exposing the plaintext bundle
/// to the caller — the password-change path.
String envelopeRewrap({
  required List<int> oldKek,
  required List<int> newKek,
  required String envelope,
}) => RustLib.instance.api.crateApiEnvelopeRewrap(
  oldKek: oldKek,
  newKek: newKek,
  envelope: envelope,
);

/// Derive a 32-byte key from `secret` and `salt` with Argon2id at the same
/// frozen cost as the OPAQUE KSF (m=64 MiB, t=3, p=1). The device-key vault
/// folds the PIN into its wrap key through this, so grinding a stolen
/// `app.db` + keychain pair costs a memory-hard derivation per PIN guess
/// instead of one SHA-256. Async so the work runs on the FRB worker pool
/// rather than the platform thread.
Future<Uint8List> argon2IdDeriveKey({
  required List<int> secret,
  required List<int> salt,
}) =>
    RustLib.instance.api.crateApiArgon2IdDeriveKey(secret: secret, salt: salt);

/// Sign a key-transition certificate binding the user's old identity key to
/// their new Curve25519 identity + wrapping keys. `old_key_type` is `"rsa"` or
/// `"curve25519"`. Returns the two detached signatures the server records.
TransitionSignatures transitionSign({
  required List<int> userId,
  required String oldKeyType,
  required String oldKeyPem,
  required String oldFingerprint,
  required String newIdentityKeyPem,
  required String newWrappingKeyPem,
  required String newFingerprint,
  required PlatformInt64 issuedAt,
  required String oldPrivateKey,
  required String newIdentityPrivateKey,
}) => RustLib.instance.api.crateApiTransitionSign(
  userId: userId,
  oldKeyType: oldKeyType,
  oldKeyPem: oldKeyPem,
  oldFingerprint: oldFingerprint,
  newIdentityKeyPem: newIdentityKeyPem,
  newWrappingKeyPem: newWrappingKeyPem,
  newFingerprint: newFingerprint,
  issuedAt: issuedAt,
  oldPrivateKey: oldPrivateKey,
  newIdentityPrivateKey: newIdentityPrivateKey,
);

/// Verify another user's transition certificate from server-supplied fields:
/// the old key's endorsement of the new keys, the new identity key's proof of
/// possession, and each fingerprint against the key it names. `user_id` must
/// be the 16 UUID bytes the caller resolved the signer as — the canonical
/// binds it, so a certificate replayed from a different account fails.
/// `old_key_spki` is the old key's member-DER (the PEM body); the signatures
/// are base64.
bool transitionVerify({
  required List<int> userId,
  required String oldKeyType,
  required List<int> oldKeySpki,
  required String oldFingerprint,
  required String newIdentityKeyPem,
  required String newWrappingKeyPem,
  required String newFingerprint,
  required PlatformInt64 issuedAt,
  required String oldSignature,
  required String newSignature,
}) => RustLib.instance.api.crateApiTransitionVerify(
  userId: userId,
  oldKeyType: oldKeyType,
  oldKeySpki: oldKeySpki,
  oldFingerprint: oldFingerprint,
  newIdentityKeyPem: newIdentityKeyPem,
  newWrappingKeyPem: newWrappingKeyPem,
  newFingerprint: newFingerprint,
  issuedAt: issuedAt,
  oldSignature: oldSignature,
  newSignature: newSignature,
);

/// Sign the key-rotation audit event with the new identity key — the first act
/// of the rotated identity, appended to the owner's audit chain so a later
/// reader sees why the signing key changed. `user_id` is the 16 raw UUID bytes;
/// the fingerprints are the hex strings held in `users.fingerprint`. Returns the
/// base64 signature submitted as `audit_event_signature`; the server re-encodes
/// the same canonical from its own record and aborts the migration if it does
/// not verify.
String signKeyRotationAudit({
  required List<int> userId,
  required String oldFingerprint,
  required String newFingerprint,
  required PlatformInt64 rotatedAt,
  required String newIdentityPrivateKey,
}) => RustLib.instance.api.crateApiSignKeyRotationAudit(
  userId: userId,
  oldFingerprint: oldFingerprint,
  newFingerprint: newFingerprint,
  rotatedAt: rotatedAt,
  newIdentityPrivateKey: newIdentityPrivateKey,
);

/// Upload a file to the Hoodik server.
///
/// Runs the full chunked-upload pipeline from the `transfer` crate:
/// concurrent chunk encryption + upload (8 parallel), CRC checksums, retry on
/// mismatch, resume support, and inline SHA-256/MD5/SHA-1/BLAKE2b hashing.
///
/// Uses `spawn_blocking` + a single-threaded tokio `LocalSet` internally so
/// that the transfer crate's `!Send` futures work within FRB's multi-threaded
/// executor.
///
/// Returns the computed file hashes as JSON.
Future<String> uploadFile({
  required String baseUrl,
  required String cookie,
  required String fileId,
  required String filePath,
  required List<int> encryptionKey,
  required String cipher,
  required Uint64List alreadyUploaded,
}) => RustLib.instance.api.crateApiUploadFile(
  baseUrl: baseUrl,
  cookie: cookie,
  fileId: fileId,
  filePath: filePath,
  encryptionKey: encryptionKey,
  cipher: cipher,
  alreadyUploaded: alreadyUploaded,
);

/// Download a file from the Hoodik server and return the decrypted bytes.
///
/// Uses the transfer crate's concurrent download pipeline (16 parallel chunk
/// fetches with sliding window, out-of-order reassembly).
Future<Uint8List> downloadFile({
  required String baseUrl,
  required String cookie,
  required String fileId,
  required BigInt fileSize,
  required BigInt chunkCount,
  required List<int> decryptionKey,
  required String cipher,
  required List<String> directUrls,
}) => RustLib.instance.api.crateApiDownloadFile(
  baseUrl: baseUrl,
  cookie: cookie,
  fileId: fileId,
  fileSize: fileSize,
  chunkCount: chunkCount,
  decryptionKey: decryptionKey,
  cipher: cipher,
  directUrls: directUrls,
);

/// Download a file and save it to a local path instead of returning bytes.
/// Better for large files — avoids holding the entire file in memory.
Future<void> downloadFileToPath({
  required String baseUrl,
  required String cookie,
  required String fileId,
  required BigInt fileSize,
  required BigInt chunkCount,
  required List<int> decryptionKey,
  required String cipher,
  required String outputPath,
  required List<String> directUrls,
}) => RustLib.instance.api.crateApiDownloadFileToPath(
  baseUrl: baseUrl,
  cookie: cookie,
  fileId: fileId,
  fileSize: fileSize,
  chunkCount: chunkCount,
  decryptionKey: decryptionKey,
  cipher: cipher,
  outputPath: outputPath,
  directUrls: directUrls,
);

/// Download encrypted chunks to a directory without decrypting.
///
/// Each chunk is saved as `{output_dir}/{chunk_index:06}.enc`.  Uses 16
/// concurrent downloads with a sliding window — same throughput as the
/// original pipeline but with ~4 MB peak memory instead of the full file.
///
/// `already_downloaded` lists chunk indices to skip (resume support).
///
/// `direct_urls`, when non-empty, holds one presigned storage URL per chunk
/// index. Those chunks are fetched straight from the bucket and carry no
/// session credentials; any index the list does not cover falls back to the
/// server, so a short or absent list degrades instead of failing.
Future<void> downloadEncryptedChunks({
  required String baseUrl,
  required String cookie,
  required String fileId,
  required BigInt fileSize,
  required BigInt chunkCount,
  required String outputDir,
  required Uint64List alreadyDownloaded,
  required List<String> directUrls,
}) => RustLib.instance.api.crateApiDownloadEncryptedChunks(
  baseUrl: baseUrl,
  cookie: cookie,
  fileId: fileId,
  fileSize: fileSize,
  chunkCount: chunkCount,
  outputDir: outputDir,
  alreadyDownloaded: alreadyDownloaded,
  directUrls: directUrls,
);

/// Download a file's encrypted chunks as one tar stream and unpack to
/// `{output_dir}/{index:06}.enc`. Uses the server's `?format=tar` endpoint
/// so the whole file arrives in a single HTTP response instead of N
/// per-chunk GETs — the decisive win on high-latency links and the
/// fallback path when the OS-native background downloader isn't
/// available (desktop Linux/Windows, self-signed certs on iOS/macOS).
///
/// `already_downloaded` lists chunk indices already cached on disk. The
/// tar endpoint itself returns the full archive — existing chunks on
/// disk are simply left untouched because the bulk extract rewrites by
/// filename. Kept in the signature to match the per-chunk fallback so
/// the pipeline can feed either implementation the same arguments.
Future<void> downloadFileAsTar({
  required String baseUrl,
  required String cookie,
  required String fileId,
  required BigInt fileSize,
  required BigInt chunkCount,
  required String outputDir,
  required Uint64List alreadyDownloaded,
}) => RustLib.instance.api.crateApiDownloadFileAsTar(
  baseUrl: baseUrl,
  cookie: cookie,
  fileId: fileId,
  fileSize: fileSize,
  chunkCount: chunkCount,
  outputDir: outputDir,
  alreadyDownloaded: alreadyDownloaded,
);

/// Upload previously-encrypted chunks from `{chunks_dir}/{index:06}.enc`
/// as a single tar stream to `POST /api/storage/{file_id}?format=tar`.
///
/// Returns the server's `chunks_stored` / `finished_upload_at` so the
/// caller can tell whether the upload completed on this attempt. Older
/// servers that don't understand `?format=tar` surface that through the
/// normal HTTP error path; the pipeline reads that signal and falls back
/// to per-chunk uploads.
Future<UploadCompleteSummary> uploadFileAsTar({
  required String baseUrl,
  required String cookie,
  required String fileId,
  required String chunksDir,
  required BigInt chunkCount,
}) => RustLib.instance.api.crateApiUploadFileAsTar(
  baseUrl: baseUrl,
  cookie: cookie,
  fileId: fileId,
  chunksDir: chunksDir,
  chunkCount: chunkCount,
);

/// Decrypt previously downloaded encrypted chunks to a single output file.
///
/// Reads chunks sequentially from `{chunks_dir}/{index:06}.enc`, decrypts
/// each with the given key+cipher, and streams plaintext to `output_path`.
/// Peak memory: ~4 MB (one chunk at a time).
Future<void> decryptChunksToFile({
  required String chunksDir,
  required BigInt chunkCount,
  required List<int> decryptionKey,
  required String cipher,
  required String outputPath,
  required String fileId,
}) => RustLib.instance.api.crateApiDecryptChunksToFile(
  chunksDir: chunksDir,
  chunkCount: chunkCount,
  decryptionKey: decryptionKey,
  cipher: cipher,
  outputPath: outputPath,
  fileId: fileId,
);

/// Unpack a tar archive of encrypted chunks into individual files.
///
/// Reads the archive at [`tar_path`] sequentially and writes every regular
/// file entry to `{output_dir}/{entry_name}`. Headers are parsed one at a
/// time and only the current entry's payload lives in memory, so archives
/// much larger than free RAM unpack without swapping.
///
/// Pure local I/O — no network, no decryption. Decryption happens later via
/// [`decrypt_chunks_to_file`]. Counterpart to [`pack_chunks_to_tar`].
void unpackTarToChunks({required String tarPath, required String outputDir}) =>
    RustLib.instance.api.crateApiUnpackTarToChunks(
      tarPath: tarPath,
      outputDir: outputDir,
    );

/// Build a tar archive containing `{chunks_dir}/{index:06}.enc` for every
/// index in `[0, chunk_count)` and write it to [`tar_path`].
///
/// Chunks are streamed one at a time into the output archive so peak memory
/// stays at one chunk (~4 MB) rather than the full archive. Pure local I/O
/// — the caller uploads the resulting file through `background_downloader`
/// so the transfer survives app suspension. Counterpart to
/// [`unpack_tar_to_chunks`].
void packChunksToTar({
  required String chunksDir,
  required BigInt chunkCount,
  required String tarPath,
}) => RustLib.instance.api.crateApiPackChunksToTar(
  chunksDir: chunksDir,
  chunkCount: chunkCount,
  tarPath: tarPath,
);

/// Poll the current progress of a transfer.
///
/// Returns (transferred, total) where:
/// - For downloads: (bytes_downloaded, total_bytes)
/// - For uploads: (chunks_completed, total_chunks)
///
/// Returns `None` if no transfer with the given file_id is active.
(BigInt, BigInt)? getTransferProgress({required String fileId}) =>
    RustLib.instance.api.crateApiGetTransferProgress(fileId: fileId);

/// Cancel an in-progress upload or download.
void cancelTransfer({required String fileId}) =>
    RustLib.instance.api.crateApiCancelTransfer(fileId: fileId);

class Ed25519KeyPair {
  final String privatePem;
  final String publicPem;

  const Ed25519KeyPair({required this.privatePem, required this.publicPem});

  @override
  int get hashCode => privatePem.hashCode ^ publicPem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Ed25519KeyPair &&
          runtimeType == other.runtimeType &&
          privatePem == other.privatePem &&
          publicPem == other.publicPem;
}

class OpaqueClientStart {
  final String state;
  final String message;

  const OpaqueClientStart({required this.state, required this.message});

  @override
  int get hashCode => state.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpaqueClientStart &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message;
}

class OpaqueLoginFinish {
  final String finalization;
  final String sessionKey;
  final String exportKey;

  const OpaqueLoginFinish({
    required this.finalization,
    required this.sessionKey,
    required this.exportKey,
  });

  @override
  int get hashCode =>
      finalization.hashCode ^ sessionKey.hashCode ^ exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpaqueLoginFinish &&
          runtimeType == other.runtimeType &&
          finalization == other.finalization &&
          sessionKey == other.sessionKey &&
          exportKey == other.exportKey;
}

class OpaqueRegisterFinish {
  final String message;
  final String exportKey;

  const OpaqueRegisterFinish({required this.message, required this.exportKey});

  @override
  int get hashCode => message.hashCode ^ exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpaqueRegisterFinish &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          exportKey == other.exportKey;
}

class RsaKeyPair {
  final String privateKeyPem;
  final String publicKeyPem;
  final String fingerprint;

  const RsaKeyPair({
    required this.privateKeyPem,
    required this.publicKeyPem,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      privateKeyPem.hashCode ^ publicKeyPem.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsaKeyPair &&
          runtimeType == other.runtimeType &&
          privateKeyPem == other.privateKeyPem &&
          publicKeyPem == other.publicKeyPem &&
          fingerprint == other.fingerprint;
}

class RsaPublicInfo {
  final String publicKeyPem;
  final String fingerprint;

  const RsaPublicInfo({required this.publicKeyPem, required this.fingerprint});

  @override
  int get hashCode => publicKeyPem.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsaPublicInfo &&
          runtimeType == other.runtimeType &&
          publicKeyPem == other.publicKeyPem &&
          fingerprint == other.fingerprint;
}

class TransitionSignatures {
  final String oldSignature;
  final String newSignature;

  const TransitionSignatures({
    required this.oldSignature,
    required this.newSignature,
  });

  @override
  int get hashCode => oldSignature.hashCode ^ newSignature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransitionSignatures &&
          runtimeType == other.runtimeType &&
          oldSignature == other.oldSignature &&
          newSignature == other.newSignature;
}

/// Minimal subset of the server's upload-complete response that the
/// Flutter pipeline needs. Matches the `chunks_stored` / `finished_upload_at`
/// fields of `transfer::types::ChunkResponse`, flattened for FFI.
class UploadCompleteSummary {
  final PlatformInt64 chunksStored;
  final PlatformInt64? finishedUploadAt;

  const UploadCompleteSummary({
    required this.chunksStored,
    this.finishedUploadAt,
  });

  @override
  int get hashCode => chunksStored.hashCode ^ finishedUploadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadCompleteSummary &&
          runtimeType == other.runtimeType &&
          chunksStored == other.chunksStored &&
          finishedUploadAt == other.finishedUploadAt;
}

class WrappingKeyPair {
  final String privatePem;
  final String publicPem;

  const WrappingKeyPair({required this.privatePem, required this.publicPem});

  @override
  int get hashCode => privatePem.hashCode ^ publicPem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WrappingKeyPair &&
          runtimeType == other.runtimeType &&
          privatePem == other.privatePem &&
          publicPem == other.publicPem;
}
