// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  Ed25519KeyPair dco_decode_ed_25519_key_pair(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OpaqueClientStart dco_decode_opaque_client_start(dynamic raw);

  @protected
  OpaqueLoginFinish dco_decode_opaque_login_finish(dynamic raw);

  @protected
  OpaqueRegisterFinish dco_decode_opaque_register_finish(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  (BigInt, BigInt)? dco_decode_opt_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  RsaKeyPair dco_decode_rsa_key_pair(dynamic raw);

  @protected
  RsaPublicInfo dco_decode_rsa_public_info(dynamic raw);

  @protected
  TransitionSignatures dco_decode_transition_signatures(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadCompleteSummary dco_decode_upload_complete_summary(dynamic raw);

  @protected
  WrappingKeyPair dco_decode_wrapping_key_pair(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt) sse_decode_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  Ed25519KeyPair sse_decode_ed_25519_key_pair(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OpaqueClientStart sse_decode_opaque_client_start(
    SseDeserializer deserializer,
  );

  @protected
  OpaqueLoginFinish sse_decode_opaque_login_finish(
    SseDeserializer deserializer,
  );

  @protected
  OpaqueRegisterFinish sse_decode_opaque_register_finish(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt)? sse_decode_opt_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  RsaKeyPair sse_decode_rsa_key_pair(SseDeserializer deserializer);

  @protected
  RsaPublicInfo sse_decode_rsa_public_info(SseDeserializer deserializer);

  @protected
  TransitionSignatures sse_decode_transition_signatures(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadCompleteSummary sse_decode_upload_complete_summary(
    SseDeserializer deserializer,
  );

  @protected
  WrappingKeyPair sse_decode_wrapping_key_pair(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_record_u_64_u_64((BigInt, BigInt) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_record_u_64_u_64(raw);
  }

  @protected
  JSAny cst_encode_ed_25519_key_pair(Ed25519KeyPair raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.privatePem),
      cst_encode_String(raw.publicPem),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_32_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_32_strict(Uint32List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_64_strict(Uint64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.inner.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_opaque_client_start(OpaqueClientStart raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.state),
      cst_encode_String(raw.message),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_opaque_login_finish(OpaqueLoginFinish raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.finalization),
      cst_encode_String(raw.sessionKey),
      cst_encode_String(raw.exportKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_opaque_register_finish(OpaqueRegisterFinish raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.message),
      cst_encode_String(raw.exportKey),
    ].jsify()!;
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_record_u_64_u_64((BigInt, BigInt)? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_record_u_64_u_64(raw);
  }

  @protected
  JSAny cst_encode_record_u_64_u_64((BigInt, BigInt) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_u_64(raw.$1), cst_encode_u_64(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_rsa_key_pair(RsaKeyPair raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.privateKeyPem),
      cst_encode_String(raw.publicKeyPem),
      cst_encode_String(raw.fingerprint),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_rsa_public_info(RsaPublicInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.publicKeyPem),
      cst_encode_String(raw.fingerprint),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_transition_signatures(TransitionSignatures raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.oldSignature),
      cst_encode_String(raw.newSignature),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_upload_complete_summary(UploadCompleteSummary raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_64(raw.chunksStored),
      cst_encode_opt_box_autoadd_i_64(raw.finishedUploadAt),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wrapping_key_pair(WrappingKeyPair raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.privatePem),
      cst_encode_String(raw.publicPem),
    ].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ed_25519_key_pair(
    Ed25519KeyPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_client_start(
    OpaqueClientStart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_login_finish(
    OpaqueLoginFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_register_finish(
    OpaqueRegisterFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rsa_key_pair(RsaKeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_rsa_public_info(RsaPublicInfo self, SseSerializer serializer);

  @protected
  void sse_encode_transition_signatures(
    TransitionSignatures self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_complete_summary(
    UploadCompleteSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wrapping_key_pair(
    WrappingKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__argon2id_derive_key(
    NativePortType port_,
    JSAny secret,
    JSAny salt,
  ) => wasmModule.wire__crate__api__argon2id_derive_key(port_, secret, salt);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__audit_event_encode_v1(
    JSAny sender_id,
    JSAny recipient_id,
    JSAny file_id,
    String action,
    int share_role,
    JSAny created_at,
  ) => wasmModule.wire__crate__api__audit_event_encode_v1(
    sender_id,
    recipient_id,
    file_id,
    action,
    share_role,
    created_at,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__audit_event_sig_input_encode_v1(
    JSAny sender_id,
    JSAny recipient_id,
    JSAny file_id,
    int action,
    int share_role_before,
    int share_role_after,
    JSAny timestamp,
  ) => wasmModule.wire__crate__api__audit_event_sig_input_encode_v1(
    sender_id,
    recipient_id,
    file_id,
    action,
    share_role_before,
    share_role_after,
    timestamp,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__base64_decode(String data) =>
      wasmModule.wire__crate__api__base64_decode(data);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__base64_encode(JSAny data) =>
      wasmModule.wire__crate__api__base64_encode(data);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cancel_transfer(String file_id) =>
      wasmModule.wire__crate__api__cancel_transfer(file_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_decrypt(
    String cipher,
    JSAny key,
    JSAny ciphertext,
  ) => wasmModule.wire__crate__api__cipher_decrypt(cipher, key, ciphertext);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_decrypt_chunk(
    String cipher,
    JSAny key,
    JSAny chunk_index,
    JSAny ciphertext,
  ) => wasmModule.wire__crate__api__cipher_decrypt_chunk(
    cipher,
    key,
    chunk_index,
    ciphertext,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_decrypt_string(
    String cipher,
    JSAny key,
    JSAny ciphertext,
  ) => wasmModule.wire__crate__api__cipher_decrypt_string(
    cipher,
    key,
    ciphertext,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_encrypt(String cipher, JSAny key, JSAny plaintext) =>
      wasmModule.wire__crate__api__cipher_encrypt(cipher, key, plaintext);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_encrypt_chunk(
    String cipher,
    JSAny key,
    JSAny chunk_index,
    JSAny plaintext,
  ) => wasmModule.wire__crate__api__cipher_encrypt_chunk(
    cipher,
    key,
    chunk_index,
    plaintext,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_encrypt_string(
    String cipher,
    JSAny key,
    JSAny plaintext,
  ) => wasmModule.wire__crate__api__cipher_encrypt_string(
    cipher,
    key,
    plaintext,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_generate_key(String cipher) =>
      wasmModule.wire__crate__api__cipher_generate_key(cipher);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__crc16_digest(JSAny data) =>
      wasmModule.wire__crate__api__crc16_digest(data);

  void wire__crate__api__decrypt_chunks_to_file(
    NativePortType port_,
    String chunks_dir,
    JSAny chunk_count,
    JSAny decryption_key,
    String cipher,
    String output_path,
    String file_id,
  ) => wasmModule.wire__crate__api__decrypt_chunks_to_file(
    port_,
    chunks_dir,
    chunk_count,
    decryption_key,
    cipher,
    output_path,
    file_id,
  );

  void wire__crate__api__download_encrypted_chunks(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    String output_dir,
    JSAny already_downloaded,
    JSAny direct_urls,
  ) => wasmModule.wire__crate__api__download_encrypted_chunks(
    port_,
    base_url,
    cookie,
    file_id,
    file_size,
    chunk_count,
    output_dir,
    already_downloaded,
    direct_urls,
  );

  void wire__crate__api__download_file(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    JSAny decryption_key,
    String cipher,
    JSAny direct_urls,
  ) => wasmModule.wire__crate__api__download_file(
    port_,
    base_url,
    cookie,
    file_id,
    file_size,
    chunk_count,
    decryption_key,
    cipher,
    direct_urls,
  );

  void wire__crate__api__download_file_as_tar(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    String output_dir,
    JSAny already_downloaded,
  ) => wasmModule.wire__crate__api__download_file_as_tar(
    port_,
    base_url,
    cookie,
    file_id,
    file_size,
    chunk_count,
    output_dir,
    already_downloaded,
  );

  void wire__crate__api__download_file_to_path(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    JSAny decryption_key,
    String cipher,
    String output_path,
    JSAny direct_urls,
  ) => wasmModule.wire__crate__api__download_file_to_path(
    port_,
    base_url,
    cookie,
    file_id,
    file_size,
    chunk_count,
    decryption_key,
    cipher,
    output_path,
    direct_urls,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_sign(String message, String private_pem) =>
      wasmModule.wire__crate__api__ed25519_sign(message, private_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_sign_bytes(JSAny message, String private_pem) =>
      wasmModule.wire__crate__api__ed25519_sign_bytes(message, private_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_verify(
    String message,
    String signature,
    String public_pem,
  ) => wasmModule.wire__crate__api__ed25519_verify(
    message,
    signature,
    public_pem,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_verify_bytes(
    JSAny message,
    String signature,
    String public_pem,
  ) => wasmModule.wire__crate__api__ed25519_verify_bytes(
    message,
    signature,
    public_pem,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__entries_encode_v1(
    JSAny file_ids,
    JSAny encrypted_keys_flat,
    JSAny encrypted_key_lengths,
  ) => wasmModule.wire__crate__api__entries_encode_v1(
    file_ids,
    encrypted_keys_flat,
    encrypted_key_lengths,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_derive_kek(JSAny export_key) =>
      wasmModule.wire__crate__api__envelope_derive_kek(export_key);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_open(JSAny kek, String envelope) =>
      wasmModule.wire__crate__api__envelope_open(kek, envelope);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_rewrap(
    JSAny old_kek,
    JSAny new_kek,
    String envelope,
  ) => wasmModule.wire__crate__api__envelope_rewrap(old_kek, new_kek, envelope);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_seal(JSAny kek, JSAny bundle) =>
      wasmModule.wire__crate__api__envelope_seal(kek, bundle);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__folder_member_list_encode_v1(
    JSAny folder_id,
    JSAny folder_owner_id,
    JSAny user_ids,
    JSAny pubkey_fingerprints,
    JSAny share_roles,
    JSAny is_owner_flags,
    JSAny signed_by_user_ids,
    JSAny members_signed_at,
  ) => wasmModule.wire__crate__api__folder_member_list_encode_v1(
    folder_id,
    folder_owner_id,
    user_ids,
    pubkey_fingerprints,
    share_roles,
    is_owner_flags,
    signed_by_user_ids,
    members_signed_at,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_ed25519_keypair() =>
      wasmModule.wire__crate__api__generate_ed25519_keypair();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_rsa_keypair() =>
      wasmModule.wire__crate__api__generate_rsa_keypair();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_wrapping_keypair() =>
      wasmModule.wire__crate__api__generate_wrapping_keypair();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_transfer_progress(String file_id) =>
      wasmModule.wire__crate__api__get_transfer_progress(file_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__member_pubkey_der(String key_type, String public_key_pem) =>
      wasmModule.wire__crate__api__member_pubkey_der(key_type, public_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__member_sig_encode_v1(
    JSAny user_id,
    JSAny pubkey_der,
    JSAny fingerprint,
    int share_role,
    JSAny signed_at,
  ) => wasmModule.wire__crate__api__member_sig_encode_v1(
    user_id,
    pubkey_der,
    fingerprint,
    share_role,
    signed_at,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_login_finish(
    String login_state,
    String credential_response,
    JSAny password,
    int m_cost,
    int t_cost,
    int p_cost,
  ) => wasmModule.wire__crate__api__opaque_client_login_finish(
    login_state,
    credential_response,
    password,
    m_cost,
    t_cost,
    p_cost,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_login_start(JSAny password) =>
      wasmModule.wire__crate__api__opaque_client_login_start(password);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_registration_finish(
    String registration_state,
    String registration_response,
    JSAny password,
  ) => wasmModule.wire__crate__api__opaque_client_registration_finish(
    registration_state,
    registration_response,
    password,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_registration_start(JSAny password) =>
      wasmModule.wire__crate__api__opaque_client_registration_start(password);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__pack_chunks_to_tar(
    String chunks_dir,
    JSAny chunk_count,
    String tar_path,
  ) => wasmModule.wire__crate__api__pack_chunks_to_tar(
    chunks_dir,
    chunk_count,
    tar_path,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_decrypt(
    String ciphertext_b64,
    String private_key_pem,
  ) =>
      wasmModule.wire__crate__api__rsa_decrypt(ciphertext_b64, private_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_encrypt(String plaintext, String public_key_pem) =>
      wasmModule.wire__crate__api__rsa_encrypt(plaintext, public_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_fingerprint_public(String public_key_pem) =>
      wasmModule.wire__crate__api__rsa_fingerprint_public(public_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_pkcs1_der_from_pem(String public_key_pem) =>
      wasmModule.wire__crate__api__rsa_pkcs1_der_from_pem(public_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_public_from_private(String private_key_pem) =>
      wasmModule.wire__crate__api__rsa_public_from_private(private_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_sign(String message, String private_key_pem) =>
      wasmModule.wire__crate__api__rsa_sign(message, private_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_sign_bytes(JSAny message, String private_key_pem) =>
      wasmModule.wire__crate__api__rsa_sign_bytes(message, private_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_verify(
    String message,
    String signature,
    String public_key_pem,
  ) => wasmModule.wire__crate__api__rsa_verify(
    message,
    signature,
    public_key_pem,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_verify_bytes(
    JSAny message,
    String signature,
    String public_key_pem,
  ) => wasmModule.wire__crate__api__rsa_verify_bytes(
    message,
    signature,
    public_key_pem,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_file_key(JSAny file_key) =>
      wasmModule.wire__crate__api__search_file_key(file_key);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_root_key(String private_key_pem) =>
      wasmModule.wire__crate__api__search_root_key(private_key_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_tag(String key_hex, String value) =>
      wasmModule.wire__crate__api__search_tag(key_hex, value);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_tag_tokens(String key_hex, String text) =>
      wasmModule.wire__crate__api__search_tag_tokens(key_hex, text);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__sha256_digest(JSAny data) =>
      wasmModule.wire__crate__api__sha256_digest(data);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__share_payload_encode_v1(
    JSAny sender_id,
    JSAny recipient_id,
    JSAny recipient_pubkey_fingerprint,
    int share_role,
    JSAny root_file_id,
    JSAny entries_hash,
    JSAny timestamp,
    JSAny nonce,
  ) => wasmModule.wire__crate__api__share_payload_encode_v1(
    sender_id,
    recipient_id,
    recipient_pubkey_fingerprint,
    share_role,
    root_file_id,
    entries_hash,
    timestamp,
    nonce,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__sign_key_rotation_audit(
    JSAny user_id,
    String old_fingerprint,
    String new_fingerprint,
    JSAny rotated_at,
    String new_identity_private_key,
  ) => wasmModule.wire__crate__api__sign_key_rotation_audit(
    user_id,
    old_fingerprint,
    new_fingerprint,
    rotated_at,
    new_identity_private_key,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__spki_fingerprint(String public_pem) =>
      wasmModule.wire__crate__api__spki_fingerprint(public_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__transition_sign(
    JSAny user_id,
    String old_key_type,
    String old_key_pem,
    String old_fingerprint,
    String new_identity_key_pem,
    String new_wrapping_key_pem,
    String new_fingerprint,
    JSAny issued_at,
    String old_private_key,
    String new_identity_private_key,
  ) => wasmModule.wire__crate__api__transition_sign(
    user_id,
    old_key_type,
    old_key_pem,
    old_fingerprint,
    new_identity_key_pem,
    new_wrapping_key_pem,
    new_fingerprint,
    issued_at,
    old_private_key,
    new_identity_private_key,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__transition_verify(
    JSAny user_id,
    String old_key_type,
    JSAny old_key_spki,
    String old_fingerprint,
    String new_identity_key_pem,
    String new_wrapping_key_pem,
    String new_fingerprint,
    JSAny issued_at,
    String old_signature,
    String new_signature,
  ) => wasmModule.wire__crate__api__transition_verify(
    user_id,
    old_key_type,
    old_key_spki,
    old_fingerprint,
    new_identity_key_pem,
    new_wrapping_key_pem,
    new_fingerprint,
    issued_at,
    old_signature,
    new_signature,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__unpack_tar_to_chunks(String tar_path, String output_dir) =>
      wasmModule.wire__crate__api__unpack_tar_to_chunks(tar_path, output_dir);

  void wire__crate__api__upload_file(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    String file_path,
    JSAny encryption_key,
    String cipher,
    JSAny already_uploaded,
  ) => wasmModule.wire__crate__api__upload_file(
    port_,
    base_url,
    cookie,
    file_id,
    file_path,
    encryption_key,
    cipher,
    already_uploaded,
  );

  void wire__crate__api__upload_file_as_tar(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    String chunks_dir,
    JSAny chunk_count,
  ) => wasmModule.wire__crate__api__upload_file_as_tar(
    port_,
    base_url,
    cookie,
    file_id,
    chunks_dir,
    chunk_count,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wrapping_unwrap(String blob, String private_pem) =>
      wasmModule.wire__crate__api__wrapping_unwrap(blob, private_pem);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wrapping_wrap(
    JSAny file_key,
    String recipient_public_pem,
  ) => wasmModule.wire__crate__api__wrapping_wrap(
    file_key,
    recipient_public_pem,
  );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__argon2id_derive_key(
    NativePortType port_,
    JSAny secret,
    JSAny salt,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__audit_event_encode_v1(
    JSAny sender_id,
    JSAny recipient_id,
    JSAny file_id,
    String action,
    int share_role,
    JSAny created_at,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__audit_event_sig_input_encode_v1(
    JSAny sender_id,
    JSAny recipient_id,
    JSAny file_id,
    int action,
    int share_role_before,
    int share_role_after,
    JSAny timestamp,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__base64_decode(String data);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__base64_encode(JSAny data);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cancel_transfer(String file_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_decrypt(String cipher, JSAny key, JSAny ciphertext);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_decrypt_chunk(
    String cipher,
    JSAny key,
    JSAny chunk_index,
    JSAny ciphertext,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_decrypt_string(
    String cipher,
    JSAny key,
    JSAny ciphertext,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_encrypt(String cipher, JSAny key, JSAny plaintext);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_encrypt_chunk(
    String cipher,
    JSAny key,
    JSAny chunk_index,
    JSAny plaintext,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_encrypt_string(
    String cipher,
    JSAny key,
    JSAny plaintext,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cipher_generate_key(String cipher);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__crc16_digest(JSAny data);

  external void wire__crate__api__decrypt_chunks_to_file(
    NativePortType port_,
    String chunks_dir,
    JSAny chunk_count,
    JSAny decryption_key,
    String cipher,
    String output_path,
    String file_id,
  );

  external void wire__crate__api__download_encrypted_chunks(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    String output_dir,
    JSAny already_downloaded,
    JSAny direct_urls,
  );

  external void wire__crate__api__download_file(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    JSAny decryption_key,
    String cipher,
    JSAny direct_urls,
  );

  external void wire__crate__api__download_file_as_tar(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    String output_dir,
    JSAny already_downloaded,
  );

  external void wire__crate__api__download_file_to_path(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    JSAny file_size,
    JSAny chunk_count,
    JSAny decryption_key,
    String cipher,
    String output_path,
    JSAny direct_urls,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_sign(String message, String private_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_sign_bytes(JSAny message, String private_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_verify(
    String message,
    String signature,
    String public_pem,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__ed25519_verify_bytes(
    JSAny message,
    String signature,
    String public_pem,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__entries_encode_v1(
    JSAny file_ids,
    JSAny encrypted_keys_flat,
    JSAny encrypted_key_lengths,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_derive_kek(JSAny export_key);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_open(JSAny kek, String envelope);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_rewrap(
    JSAny old_kek,
    JSAny new_kek,
    String envelope,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__envelope_seal(JSAny kek, JSAny bundle);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__folder_member_list_encode_v1(
    JSAny folder_id,
    JSAny folder_owner_id,
    JSAny user_ids,
    JSAny pubkey_fingerprints,
    JSAny share_roles,
    JSAny is_owner_flags,
    JSAny signed_by_user_ids,
    JSAny members_signed_at,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_ed25519_keypair();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_rsa_keypair();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_wrapping_keypair();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_transfer_progress(String file_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__member_pubkey_der(String key_type, String public_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__member_sig_encode_v1(
    JSAny user_id,
    JSAny pubkey_der,
    JSAny fingerprint,
    int share_role,
    JSAny signed_at,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_login_finish(
    String login_state,
    String credential_response,
    JSAny password,
    int m_cost,
    int t_cost,
    int p_cost,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_login_start(JSAny password);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_registration_finish(
    String registration_state,
    String registration_response,
    JSAny password,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__opaque_client_registration_start(JSAny password);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__pack_chunks_to_tar(
    String chunks_dir,
    JSAny chunk_count,
    String tar_path,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_decrypt(String ciphertext_b64, String private_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_encrypt(String plaintext, String public_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_fingerprint_public(String public_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_pkcs1_der_from_pem(String public_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_public_from_private(String private_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_sign(String message, String private_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_sign_bytes(JSAny message, String private_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_verify(
    String message,
    String signature,
    String public_key_pem,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__rsa_verify_bytes(
    JSAny message,
    String signature,
    String public_key_pem,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_file_key(JSAny file_key);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_root_key(String private_key_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_tag(String key_hex, String value);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__search_tag_tokens(String key_hex, String text);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__sha256_digest(JSAny data);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__share_payload_encode_v1(
    JSAny sender_id,
    JSAny recipient_id,
    JSAny recipient_pubkey_fingerprint,
    int share_role,
    JSAny root_file_id,
    JSAny entries_hash,
    JSAny timestamp,
    JSAny nonce,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__sign_key_rotation_audit(
    JSAny user_id,
    String old_fingerprint,
    String new_fingerprint,
    JSAny rotated_at,
    String new_identity_private_key,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__spki_fingerprint(String public_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__transition_sign(
    JSAny user_id,
    String old_key_type,
    String old_key_pem,
    String old_fingerprint,
    String new_identity_key_pem,
    String new_wrapping_key_pem,
    String new_fingerprint,
    JSAny issued_at,
    String old_private_key,
    String new_identity_private_key,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__transition_verify(
    JSAny user_id,
    String old_key_type,
    JSAny old_key_spki,
    String old_fingerprint,
    String new_identity_key_pem,
    String new_wrapping_key_pem,
    String new_fingerprint,
    JSAny issued_at,
    String old_signature,
    String new_signature,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__unpack_tar_to_chunks(String tar_path, String output_dir);

  external void wire__crate__api__upload_file(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    String file_path,
    JSAny encryption_key,
    String cipher,
    JSAny already_uploaded,
  );

  external void wire__crate__api__upload_file_as_tar(
    NativePortType port_,
    String base_url,
    String cookie,
    String file_id,
    String chunks_dir,
    JSAny chunk_count,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wrapping_unwrap(String blob, String private_pem);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wrapping_wrap(JSAny file_key, String recipient_public_pem);
}
