// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  Ed25519KeyPair dco_decode_ed_25519_key_pair(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OpaqueClientStart dco_decode_opaque_client_start(dynamic raw);

  @protected
  OpaqueLoginFinish dco_decode_opaque_login_finish(dynamic raw);

  @protected
  OpaqueRegisterFinish dco_decode_opaque_register_finish(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  (BigInt, BigInt)? dco_decode_opt_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  RsaKeyPair dco_decode_rsa_key_pair(dynamic raw);

  @protected
  RsaPublicInfo dco_decode_rsa_public_info(dynamic raw);

  @protected
  TransitionSignatures dco_decode_transition_signatures(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadCompleteSummary dco_decode_upload_complete_summary(dynamic raw);

  @protected
  WrappingKeyPair dco_decode_wrapping_key_pair(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt) sse_decode_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  Ed25519KeyPair sse_decode_ed_25519_key_pair(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OpaqueClientStart sse_decode_opaque_client_start(
    SseDeserializer deserializer,
  );

  @protected
  OpaqueLoginFinish sse_decode_opaque_login_finish(
    SseDeserializer deserializer,
  );

  @protected
  OpaqueRegisterFinish sse_decode_opaque_register_finish(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt)? sse_decode_opt_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  RsaKeyPair sse_decode_rsa_key_pair(SseDeserializer deserializer);

  @protected
  RsaPublicInfo sse_decode_rsa_public_info(SseDeserializer deserializer);

  @protected
  TransitionSignatures sse_decode_transition_signatures(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadCompleteSummary sse_decode_upload_complete_summary(
    SseDeserializer deserializer,
  );

  @protected
  WrappingKeyPair sse_decode_wrapping_key_pair(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_record_u_64_u_64>
  cst_encode_box_autoadd_record_u_64_u_64((BigInt, BigInt) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_record_u_64_u_64();
    cst_api_fill_to_wire_record_u_64_u_64(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_32_loose> cst_encode_list_prim_u_32_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_32_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_32_strict> cst_encode_list_prim_u_32_strict(
    Uint32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_64_strict> cst_encode_list_prim_u_64_strict(
    Uint64List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_64_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw.inner);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_record_u_64_u_64>
  cst_encode_opt_box_autoadd_record_u_64_u_64((BigInt, BigInt)? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_record_u_64_u_64(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt) apiObj,
    ffi.Pointer<wire_cst_record_u_64_u_64> wireObj,
  ) {
    cst_api_fill_to_wire_record_u_64_u_64(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_ed_25519_key_pair(
    Ed25519KeyPair apiObj,
    wire_cst_ed_25519_key_pair wireObj,
  ) {
    wireObj.private_pem = cst_encode_String(apiObj.privatePem);
    wireObj.public_pem = cst_encode_String(apiObj.publicPem);
  }

  @protected
  void cst_api_fill_to_wire_opaque_client_start(
    OpaqueClientStart apiObj,
    wire_cst_opaque_client_start wireObj,
  ) {
    wireObj.state = cst_encode_String(apiObj.state);
    wireObj.message = cst_encode_String(apiObj.message);
  }

  @protected
  void cst_api_fill_to_wire_opaque_login_finish(
    OpaqueLoginFinish apiObj,
    wire_cst_opaque_login_finish wireObj,
  ) {
    wireObj.finalization = cst_encode_String(apiObj.finalization);
    wireObj.session_key = cst_encode_String(apiObj.sessionKey);
    wireObj.export_key = cst_encode_String(apiObj.exportKey);
  }

  @protected
  void cst_api_fill_to_wire_opaque_register_finish(
    OpaqueRegisterFinish apiObj,
    wire_cst_opaque_register_finish wireObj,
  ) {
    wireObj.message = cst_encode_String(apiObj.message);
    wireObj.export_key = cst_encode_String(apiObj.exportKey);
  }

  @protected
  void cst_api_fill_to_wire_record_u_64_u_64(
    (BigInt, BigInt) apiObj,
    wire_cst_record_u_64_u_64 wireObj,
  ) {
    wireObj.field0 = cst_encode_u_64(apiObj.$1);
    wireObj.field1 = cst_encode_u_64(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_rsa_key_pair(
    RsaKeyPair apiObj,
    wire_cst_rsa_key_pair wireObj,
  ) {
    wireObj.private_key_pem = cst_encode_String(apiObj.privateKeyPem);
    wireObj.public_key_pem = cst_encode_String(apiObj.publicKeyPem);
    wireObj.fingerprint = cst_encode_String(apiObj.fingerprint);
  }

  @protected
  void cst_api_fill_to_wire_rsa_public_info(
    RsaPublicInfo apiObj,
    wire_cst_rsa_public_info wireObj,
  ) {
    wireObj.public_key_pem = cst_encode_String(apiObj.publicKeyPem);
    wireObj.fingerprint = cst_encode_String(apiObj.fingerprint);
  }

  @protected
  void cst_api_fill_to_wire_transition_signatures(
    TransitionSignatures apiObj,
    wire_cst_transition_signatures wireObj,
  ) {
    wireObj.old_signature = cst_encode_String(apiObj.oldSignature);
    wireObj.new_signature = cst_encode_String(apiObj.newSignature);
  }

  @protected
  void cst_api_fill_to_wire_upload_complete_summary(
    UploadCompleteSummary apiObj,
    wire_cst_upload_complete_summary wireObj,
  ) {
    wireObj.chunks_stored = cst_encode_i_64(apiObj.chunksStored);
    wireObj.finished_upload_at = cst_encode_opt_box_autoadd_i_64(
      apiObj.finishedUploadAt,
    );
  }

  @protected
  void cst_api_fill_to_wire_wrapping_key_pair(
    WrappingKeyPair apiObj,
    wire_cst_wrapping_key_pair wireObj,
  ) {
    wireObj.private_pem = cst_encode_String(apiObj.privatePem);
    wireObj.public_pem = cst_encode_String(apiObj.publicPem);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ed_25519_key_pair(
    Ed25519KeyPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_client_start(
    OpaqueClientStart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_login_finish(
    OpaqueLoginFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_register_finish(
    OpaqueRegisterFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rsa_key_pair(RsaKeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_rsa_public_info(RsaPublicInfo self, SseSerializer serializer);

  @protected
  void sse_encode_transition_signatures(
    TransitionSignatures self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_complete_summary(
    UploadCompleteSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wrapping_key_pair(
    WrappingKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__argon2id_derive_key(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> secret,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> salt,
  ) {
    return _wire__crate__api__argon2id_derive_key(port_, secret, salt);
  }

  late final _wire__crate__api__argon2id_derive_keyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__argon2id_derive_key');
  late final _wire__crate__api__argon2id_derive_key =
      _wire__crate__api__argon2id_derive_keyPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__audit_event_encode_v1(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> sender_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> recipient_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> file_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> action,
    int share_role,
    int created_at,
  ) {
    return _wire__crate__api__audit_event_encode_v1(
      sender_id,
      recipient_id,
      file_id,
      action,
      share_role,
      created_at,
    );
  }

  late final _wire__crate__api__audit_event_encode_v1Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint8,
            ffi.Int64,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__audit_event_encode_v1');
  late final _wire__crate__api__audit_event_encode_v1 =
      _wire__crate__api__audit_event_encode_v1Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__audit_event_sig_input_encode_v1(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> sender_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> recipient_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> file_id,
    int action,
    int share_role_before,
    int share_role_after,
    int timestamp,
  ) {
    return _wire__crate__api__audit_event_sig_input_encode_v1(
      sender_id,
      recipient_id,
      file_id,
      action,
      share_role_before,
      share_role_after,
      timestamp,
    );
  }

  late final _wire__crate__api__audit_event_sig_input_encode_v1Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Uint8,
            ffi.Uint8,
            ffi.Uint8,
            ffi.Int64,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__audit_event_sig_input_encode_v1');
  late final _wire__crate__api__audit_event_sig_input_encode_v1 =
      _wire__crate__api__audit_event_sig_input_encode_v1Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              int,
              int,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__base64_decode(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> data,
  ) {
    return _wire__crate__api__base64_decode(data);
  }

  late final _wire__crate__api__base64_decodePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__base64_decode');
  late final _wire__crate__api__base64_decode =
      _wire__crate__api__base64_decodePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__base64_encode(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__crate__api__base64_encode(data);
  }

  late final _wire__crate__api__base64_encodePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__base64_encode');
  late final _wire__crate__api__base64_encode =
      _wire__crate__api__base64_encodePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cancel_transfer(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
  ) {
    return _wire__crate__api__cancel_transfer(file_id);
  }

  late final _wire__crate__api__cancel_transferPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cancel_transfer');
  late final _wire__crate__api__cancel_transfer =
      _wire__crate__api__cancel_transferPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_decrypt(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> ciphertext,
  ) {
    return _wire__crate__api__cipher_decrypt(cipher, key, ciphertext);
  }

  late final _wire__crate__api__cipher_decryptPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_decrypt');
  late final _wire__crate__api__cipher_decrypt =
      _wire__crate__api__cipher_decryptPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_decrypt_chunk(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    int chunk_index,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> ciphertext,
  ) {
    return _wire__crate__api__cipher_decrypt_chunk(
      cipher,
      key,
      chunk_index,
      ciphertext,
    );
  }

  late final _wire__crate__api__cipher_decrypt_chunkPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_decrypt_chunk');
  late final _wire__crate__api__cipher_decrypt_chunk =
      _wire__crate__api__cipher_decrypt_chunkPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_decrypt_string(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> ciphertext,
  ) {
    return _wire__crate__api__cipher_decrypt_string(cipher, key, ciphertext);
  }

  late final _wire__crate__api__cipher_decrypt_stringPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_decrypt_string');
  late final _wire__crate__api__cipher_decrypt_string =
      _wire__crate__api__cipher_decrypt_stringPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_encrypt(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> plaintext,
  ) {
    return _wire__crate__api__cipher_encrypt(cipher, key, plaintext);
  }

  late final _wire__crate__api__cipher_encryptPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_encrypt');
  late final _wire__crate__api__cipher_encrypt =
      _wire__crate__api__cipher_encryptPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_encrypt_chunk(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    int chunk_index,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> plaintext,
  ) {
    return _wire__crate__api__cipher_encrypt_chunk(
      cipher,
      key,
      chunk_index,
      plaintext,
    );
  }

  late final _wire__crate__api__cipher_encrypt_chunkPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_encrypt_chunk');
  late final _wire__crate__api__cipher_encrypt_chunk =
      _wire__crate__api__cipher_encrypt_chunkPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_encrypt_string(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> plaintext,
  ) {
    return _wire__crate__api__cipher_encrypt_string(cipher, key, plaintext);
  }

  late final _wire__crate__api__cipher_encrypt_stringPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_encrypt_string');
  late final _wire__crate__api__cipher_encrypt_string =
      _wire__crate__api__cipher_encrypt_stringPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cipher_generate_key(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
  ) {
    return _wire__crate__api__cipher_generate_key(cipher);
  }

  late final _wire__crate__api__cipher_generate_keyPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__cipher_generate_key');
  late final _wire__crate__api__cipher_generate_key =
      _wire__crate__api__cipher_generate_keyPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__crc16_digest(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__crate__api__crc16_digest(data);
  }

  late final _wire__crate__api__crc16_digestPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__crc16_digest');
  late final _wire__crate__api__crc16_digest =
      _wire__crate__api__crc16_digestPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  void wire__crate__api__decrypt_chunks_to_file(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> chunks_dir,
    int chunk_count,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> decryption_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
  ) {
    return _wire__crate__api__decrypt_chunks_to_file(
      port_,
      chunks_dir,
      chunk_count,
      decryption_key,
      cipher,
      output_path,
      file_id,
    );
  }

  late final _wire__crate__api__decrypt_chunks_to_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__decrypt_chunks_to_file');
  late final _wire__crate__api__decrypt_chunks_to_file =
      _wire__crate__api__decrypt_chunks_to_filePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__download_encrypted_chunks(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cookie,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
    int file_size,
    int chunk_count,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_dir,
    ffi.Pointer<wire_cst_list_prim_u_64_strict> already_downloaded,
  ) {
    return _wire__crate__api__download_encrypted_chunks(
      port_,
      base_url,
      cookie,
      file_id,
      file_size,
      chunk_count,
      output_dir,
      already_downloaded,
    );
  }

  late final _wire__crate__api__download_encrypted_chunksPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_64_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__download_encrypted_chunks');
  late final _wire__crate__api__download_encrypted_chunks =
      _wire__crate__api__download_encrypted_chunksPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_64_strict>,
            )
          >();

  void wire__crate__api__download_file(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cookie,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
    int file_size,
    int chunk_count,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> decryption_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
  ) {
    return _wire__crate__api__download_file(
      port_,
      base_url,
      cookie,
      file_id,
      file_size,
      chunk_count,
      decryption_key,
      cipher,
    );
  }

  late final _wire__crate__api__download_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__download_file');
  late final _wire__crate__api__download_file =
      _wire__crate__api__download_filePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__download_file_as_tar(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cookie,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
    int file_size,
    int chunk_count,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_dir,
    ffi.Pointer<wire_cst_list_prim_u_64_strict> already_downloaded,
  ) {
    return _wire__crate__api__download_file_as_tar(
      port_,
      base_url,
      cookie,
      file_id,
      file_size,
      chunk_count,
      output_dir,
      already_downloaded,
    );
  }

  late final _wire__crate__api__download_file_as_tarPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_64_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__download_file_as_tar');
  late final _wire__crate__api__download_file_as_tar =
      _wire__crate__api__download_file_as_tarPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_64_strict>,
            )
          >();

  void wire__crate__api__download_file_to_path(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cookie,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
    int file_size,
    int chunk_count,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> decryption_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_path,
  ) {
    return _wire__crate__api__download_file_to_path(
      port_,
      base_url,
      cookie,
      file_id,
      file_size,
      chunk_count,
      decryption_key,
      cipher,
      output_path,
    );
  }

  late final _wire__crate__api__download_file_to_pathPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__download_file_to_path');
  late final _wire__crate__api__download_file_to_path =
      _wire__crate__api__download_file_to_pathPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__ed25519_sign(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_pem,
  ) {
    return _wire__crate__api__ed25519_sign(message, private_pem);
  }

  late final _wire__crate__api__ed25519_signPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__ed25519_sign');
  late final _wire__crate__api__ed25519_sign =
      _wire__crate__api__ed25519_signPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__ed25519_sign_bytes(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_pem,
  ) {
    return _wire__crate__api__ed25519_sign_bytes(message, private_pem);
  }

  late final _wire__crate__api__ed25519_sign_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__ed25519_sign_bytes');
  late final _wire__crate__api__ed25519_sign_bytes =
      _wire__crate__api__ed25519_sign_bytesPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__ed25519_verify(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> signature,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_pem,
  ) {
    return _wire__crate__api__ed25519_verify(message, signature, public_pem);
  }

  late final _wire__crate__api__ed25519_verifyPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__ed25519_verify');
  late final _wire__crate__api__ed25519_verify =
      _wire__crate__api__ed25519_verifyPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__ed25519_verify_bytes(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> signature,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_pem,
  ) {
    return _wire__crate__api__ed25519_verify_bytes(
      message,
      signature,
      public_pem,
    );
  }

  late final _wire__crate__api__ed25519_verify_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__ed25519_verify_bytes');
  late final _wire__crate__api__ed25519_verify_bytes =
      _wire__crate__api__ed25519_verify_bytesPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__entries_encode_v1(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> file_ids,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> encrypted_keys_flat,
    ffi.Pointer<wire_cst_list_prim_u_32_loose> encrypted_key_lengths,
  ) {
    return _wire__crate__api__entries_encode_v1(
      file_ids,
      encrypted_keys_flat,
      encrypted_key_lengths,
    );
  }

  late final _wire__crate__api__entries_encode_v1Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_32_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__entries_encode_v1');
  late final _wire__crate__api__entries_encode_v1 =
      _wire__crate__api__entries_encode_v1Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_32_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__envelope_derive_kek(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> export_key,
  ) {
    return _wire__crate__api__envelope_derive_kek(export_key);
  }

  late final _wire__crate__api__envelope_derive_kekPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__envelope_derive_kek');
  late final _wire__crate__api__envelope_derive_kek =
      _wire__crate__api__envelope_derive_kekPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__envelope_open(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> kek,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> envelope,
  ) {
    return _wire__crate__api__envelope_open(kek, envelope);
  }

  late final _wire__crate__api__envelope_openPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__envelope_open');
  late final _wire__crate__api__envelope_open =
      _wire__crate__api__envelope_openPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__envelope_rewrap(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> old_kek,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> new_kek,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> envelope,
  ) {
    return _wire__crate__api__envelope_rewrap(old_kek, new_kek, envelope);
  }

  late final _wire__crate__api__envelope_rewrapPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__envelope_rewrap');
  late final _wire__crate__api__envelope_rewrap =
      _wire__crate__api__envelope_rewrapPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__envelope_seal(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> kek,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bundle,
  ) {
    return _wire__crate__api__envelope_seal(kek, bundle);
  }

  late final _wire__crate__api__envelope_sealPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__envelope_seal');
  late final _wire__crate__api__envelope_seal =
      _wire__crate__api__envelope_sealPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__folder_member_list_encode_v1(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> folder_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> folder_owner_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> user_ids,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> pubkey_fingerprints,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> share_roles,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> is_owner_flags,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signed_by_user_ids,
    int members_signed_at,
  ) {
    return _wire__crate__api__folder_member_list_encode_v1(
      folder_id,
      folder_owner_id,
      user_ids,
      pubkey_fingerprints,
      share_roles,
      is_owner_flags,
      signed_by_user_ids,
      members_signed_at,
    );
  }

  late final _wire__crate__api__folder_member_list_encode_v1Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Int64,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__folder_member_list_encode_v1');
  late final _wire__crate__api__folder_member_list_encode_v1 =
      _wire__crate__api__folder_member_list_encode_v1Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__generate_ed25519_keypair() {
    return _wire__crate__api__generate_ed25519_keypair();
  }

  late final _wire__crate__api__generate_ed25519_keypairPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_hoodik_app_wire__crate__api__generate_ed25519_keypair',
      );
  late final _wire__crate__api__generate_ed25519_keypair =
      _wire__crate__api__generate_ed25519_keypairPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__generate_rsa_keypair() {
    return _wire__crate__api__generate_rsa_keypair();
  }

  late final _wire__crate__api__generate_rsa_keypairPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_hoodik_app_wire__crate__api__generate_rsa_keypair',
      );
  late final _wire__crate__api__generate_rsa_keypair =
      _wire__crate__api__generate_rsa_keypairPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__generate_wrapping_keypair() {
    return _wire__crate__api__generate_wrapping_keypair();
  }

  late final _wire__crate__api__generate_wrapping_keypairPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_hoodik_app_wire__crate__api__generate_wrapping_keypair',
      );
  late final _wire__crate__api__generate_wrapping_keypair =
      _wire__crate__api__generate_wrapping_keypairPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_transfer_progress(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
  ) {
    return _wire__crate__api__get_transfer_progress(file_id);
  }

  late final _wire__crate__api__get_transfer_progressPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__get_transfer_progress');
  late final _wire__crate__api__get_transfer_progress =
      _wire__crate__api__get_transfer_progressPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__member_pubkey_der(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> key_type,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem,
  ) {
    return _wire__crate__api__member_pubkey_der(key_type, public_key_pem);
  }

  late final _wire__crate__api__member_pubkey_derPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__member_pubkey_der');
  late final _wire__crate__api__member_pubkey_der =
      _wire__crate__api__member_pubkey_derPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__member_sig_encode_v1(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> user_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> pubkey_der,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> fingerprint,
    int share_role,
    int signed_at,
  ) {
    return _wire__crate__api__member_sig_encode_v1(
      user_id,
      pubkey_der,
      fingerprint,
      share_role,
      signed_at,
    );
  }

  late final _wire__crate__api__member_sig_encode_v1Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Uint8,
            ffi.Int64,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__member_sig_encode_v1');
  late final _wire__crate__api__member_sig_encode_v1 =
      _wire__crate__api__member_sig_encode_v1Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__opaque_client_login_finish(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> login_state,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> credential_response,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> password,
    int m_cost,
    int t_cost,
    int p_cost,
  ) {
    return _wire__crate__api__opaque_client_login_finish(
      login_state,
      credential_response,
      password,
      m_cost,
      t_cost,
      p_cost,
    );
  }

  late final _wire__crate__api__opaque_client_login_finishPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__opaque_client_login_finish');
  late final _wire__crate__api__opaque_client_login_finish =
      _wire__crate__api__opaque_client_login_finishPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              int,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__opaque_client_login_start(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> password,
  ) {
    return _wire__crate__api__opaque_client_login_start(password);
  }

  late final _wire__crate__api__opaque_client_login_startPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__opaque_client_login_start');
  late final _wire__crate__api__opaque_client_login_start =
      _wire__crate__api__opaque_client_login_startPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__opaque_client_registration_finish(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> registration_state,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> registration_response,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> password,
  ) {
    return _wire__crate__api__opaque_client_registration_finish(
      registration_state,
      registration_response,
      password,
    );
  }

  late final _wire__crate__api__opaque_client_registration_finishPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >(
        'frbgen_hoodik_app_wire__crate__api__opaque_client_registration_finish',
      );
  late final _wire__crate__api__opaque_client_registration_finish =
      _wire__crate__api__opaque_client_registration_finishPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__opaque_client_registration_start(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> password,
  ) {
    return _wire__crate__api__opaque_client_registration_start(password);
  }

  late final _wire__crate__api__opaque_client_registration_startPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__opaque_client_registration_start');
  late final _wire__crate__api__opaque_client_registration_start =
      _wire__crate__api__opaque_client_registration_startPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__pack_chunks_to_tar(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> chunks_dir,
    int chunk_count,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tar_path,
  ) {
    return _wire__crate__api__pack_chunks_to_tar(
      chunks_dir,
      chunk_count,
      tar_path,
    );
  }

  late final _wire__crate__api__pack_chunks_to_tarPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__pack_chunks_to_tar');
  late final _wire__crate__api__pack_chunks_to_tar =
      _wire__crate__api__pack_chunks_to_tarPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__rsa_decrypt(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> ciphertext_b64,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_key_pem,
  ) {
    return _wire__crate__api__rsa_decrypt(ciphertext_b64, private_key_pem);
  }

  late final _wire__crate__api__rsa_decryptPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_decrypt');
  late final _wire__crate__api__rsa_decrypt = _wire__crate__api__rsa_decryptPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__rsa_encrypt(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> plaintext,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem,
  ) {
    return _wire__crate__api__rsa_encrypt(plaintext, public_key_pem);
  }

  late final _wire__crate__api__rsa_encryptPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_encrypt');
  late final _wire__crate__api__rsa_encrypt = _wire__crate__api__rsa_encryptPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__rsa_fingerprint_public(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem,
  ) {
    return _wire__crate__api__rsa_fingerprint_public(public_key_pem);
  }

  late final _wire__crate__api__rsa_fingerprint_publicPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_fingerprint_public');
  late final _wire__crate__api__rsa_fingerprint_public =
      _wire__crate__api__rsa_fingerprint_publicPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__rsa_pkcs1_der_from_pem(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem,
  ) {
    return _wire__crate__api__rsa_pkcs1_der_from_pem(public_key_pem);
  }

  late final _wire__crate__api__rsa_pkcs1_der_from_pemPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_pkcs1_der_from_pem');
  late final _wire__crate__api__rsa_pkcs1_der_from_pem =
      _wire__crate__api__rsa_pkcs1_der_from_pemPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__rsa_public_from_private(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_key_pem,
  ) {
    return _wire__crate__api__rsa_public_from_private(private_key_pem);
  }

  late final _wire__crate__api__rsa_public_from_privatePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_public_from_private');
  late final _wire__crate__api__rsa_public_from_private =
      _wire__crate__api__rsa_public_from_privatePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__rsa_sign(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_key_pem,
  ) {
    return _wire__crate__api__rsa_sign(message, private_key_pem);
  }

  late final _wire__crate__api__rsa_signPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_sign');
  late final _wire__crate__api__rsa_sign = _wire__crate__api__rsa_signPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__rsa_sign_bytes(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_key_pem,
  ) {
    return _wire__crate__api__rsa_sign_bytes(message, private_key_pem);
  }

  late final _wire__crate__api__rsa_sign_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_sign_bytes');
  late final _wire__crate__api__rsa_sign_bytes =
      _wire__crate__api__rsa_sign_bytesPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__rsa_verify(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> signature,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem,
  ) {
    return _wire__crate__api__rsa_verify(message, signature, public_key_pem);
  }

  late final _wire__crate__api__rsa_verifyPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_verify');
  late final _wire__crate__api__rsa_verify = _wire__crate__api__rsa_verifyPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__rsa_verify_bytes(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> signature,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem,
  ) {
    return _wire__crate__api__rsa_verify_bytes(
      message,
      signature,
      public_key_pem,
    );
  }

  late final _wire__crate__api__rsa_verify_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__rsa_verify_bytes');
  late final _wire__crate__api__rsa_verify_bytes =
      _wire__crate__api__rsa_verify_bytesPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__sha256_digest(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__crate__api__sha256_digest(data);
  }

  late final _wire__crate__api__sha256_digestPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__sha256_digest');
  late final _wire__crate__api__sha256_digest =
      _wire__crate__api__sha256_digestPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__share_payload_encode_v1(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> sender_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> recipient_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> recipient_pubkey_fingerprint,
    int share_role,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> root_file_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> entries_hash,
    int timestamp,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> nonce,
  ) {
    return _wire__crate__api__share_payload_encode_v1(
      sender_id,
      recipient_id,
      recipient_pubkey_fingerprint,
      share_role,
      root_file_id,
      entries_hash,
      timestamp,
      nonce,
    );
  }

  late final _wire__crate__api__share_payload_encode_v1Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Uint8,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__share_payload_encode_v1');
  late final _wire__crate__api__share_payload_encode_v1 =
      _wire__crate__api__share_payload_encode_v1Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__sign_key_rotation_audit(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> user_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_fingerprint,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_fingerprint,
    int rotated_at,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_identity_private_key,
  ) {
    return _wire__crate__api__sign_key_rotation_audit(
      user_id,
      old_fingerprint,
      new_fingerprint,
      rotated_at,
      new_identity_private_key,
    );
  }

  late final _wire__crate__api__sign_key_rotation_auditPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__sign_key_rotation_audit');
  late final _wire__crate__api__sign_key_rotation_audit =
      _wire__crate__api__sign_key_rotation_auditPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__spki_fingerprint(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_pem,
  ) {
    return _wire__crate__api__spki_fingerprint(public_pem);
  }

  late final _wire__crate__api__spki_fingerprintPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__spki_fingerprint');
  late final _wire__crate__api__spki_fingerprint =
      _wire__crate__api__spki_fingerprintPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__tokenize_and_hash(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  ) {
    return _wire__crate__api__tokenize_and_hash(text);
  }

  late final _wire__crate__api__tokenize_and_hashPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__tokenize_and_hash');
  late final _wire__crate__api__tokenize_and_hash =
      _wire__crate__api__tokenize_and_hashPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__transition_sign(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> user_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_key_type,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_key_pem,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_fingerprint,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_identity_key_pem,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_wrapping_key_pem,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_fingerprint,
    int issued_at,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_private_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_identity_private_key,
  ) {
    return _wire__crate__api__transition_sign(
      user_id,
      old_key_type,
      old_key_pem,
      old_fingerprint,
      new_identity_key_pem,
      new_wrapping_key_pem,
      new_fingerprint,
      issued_at,
      old_private_key,
      new_identity_private_key,
    );
  }

  late final _wire__crate__api__transition_signPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__transition_sign');
  late final _wire__crate__api__transition_sign =
      _wire__crate__api__transition_signPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__transition_verify(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> user_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_key_type,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> old_key_spki,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_fingerprint,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_identity_key_pem,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_wrapping_key_pem,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_fingerprint,
    int issued_at,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> old_signature,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> new_signature,
  ) {
    return _wire__crate__api__transition_verify(
      user_id,
      old_key_type,
      old_key_spki,
      old_fingerprint,
      new_identity_key_pem,
      new_wrapping_key_pem,
      new_fingerprint,
      issued_at,
      old_signature,
      new_signature,
    );
  }

  late final _wire__crate__api__transition_verifyPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__transition_verify');
  late final _wire__crate__api__transition_verify =
      _wire__crate__api__transition_verifyPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__unpack_tar_to_chunks(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tar_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_dir,
  ) {
    return _wire__crate__api__unpack_tar_to_chunks(tar_path, output_dir);
  }

  late final _wire__crate__api__unpack_tar_to_chunksPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__unpack_tar_to_chunks');
  late final _wire__crate__api__unpack_tar_to_chunks =
      _wire__crate__api__unpack_tar_to_chunksPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__upload_file(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cookie,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> encryption_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cipher,
    ffi.Pointer<wire_cst_list_prim_u_64_strict> already_uploaded,
  ) {
    return _wire__crate__api__upload_file(
      port_,
      base_url,
      cookie,
      file_id,
      file_path,
      encryption_key,
      cipher,
      already_uploaded,
    );
  }

  late final _wire__crate__api__upload_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_64_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__upload_file');
  late final _wire__crate__api__upload_file = _wire__crate__api__upload_filePtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_64_strict>,
        )
      >();

  void wire__crate__api__upload_file_as_tar(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cookie,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> chunks_dir,
    int chunk_count,
  ) {
    return _wire__crate__api__upload_file_as_tar(
      port_,
      base_url,
      cookie,
      file_id,
      chunks_dir,
      chunk_count,
    );
  }

  late final _wire__crate__api__upload_file_as_tarPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint64,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__upload_file_as_tar');
  late final _wire__crate__api__upload_file_as_tar =
      _wire__crate__api__upload_file_as_tarPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__wrapping_unwrap(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> blob,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> private_pem,
  ) {
    return _wire__crate__api__wrapping_unwrap(blob, private_pem);
  }

  late final _wire__crate__api__wrapping_unwrapPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__wrapping_unwrap');
  late final _wire__crate__api__wrapping_unwrap =
      _wire__crate__api__wrapping_unwrapPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__wrapping_wrap(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> file_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> recipient_public_pem,
  ) {
    return _wire__crate__api__wrapping_wrap(file_key, recipient_public_pem);
  }

  late final _wire__crate__api__wrapping_wrapPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_hoodik_app_wire__crate__api__wrapping_wrap');
  late final _wire__crate__api__wrapping_wrap =
      _wire__crate__api__wrapping_wrapPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(int value) {
    return _cst_new_box_autoadd_i_64(value);
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
        'frbgen_hoodik_app_cst_new_box_autoadd_i_64',
      );
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_record_u_64_u_64>
  cst_new_box_autoadd_record_u_64_u_64() {
    return _cst_new_box_autoadd_record_u_64_u_64();
  }

  late final _cst_new_box_autoadd_record_u_64_u_64Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_record_u_64_u_64> Function()>
      >('frbgen_hoodik_app_cst_new_box_autoadd_record_u_64_u_64');
  late final _cst_new_box_autoadd_record_u_64_u_64 =
      _cst_new_box_autoadd_record_u_64_u_64Ptr
          .asFunction<ffi.Pointer<wire_cst_record_u_64_u_64> Function()>();

  ffi.Pointer<wire_cst_list_prim_u_32_loose> cst_new_list_prim_u_32_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_32_loose(len);
  }

  late final _cst_new_list_prim_u_32_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_32_loose> Function(ffi.Int32)
        >
      >('frbgen_hoodik_app_cst_new_list_prim_u_32_loose');
  late final _cst_new_list_prim_u_32_loose = _cst_new_list_prim_u_32_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_32_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_32_strict> cst_new_list_prim_u_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_32_strict(len);
  }

  late final _cst_new_list_prim_u_32_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_32_strict> Function(ffi.Int32)
        >
      >('frbgen_hoodik_app_cst_new_list_prim_u_32_strict');
  late final _cst_new_list_prim_u_32_strict = _cst_new_list_prim_u_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_64_strict> cst_new_list_prim_u_64_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_64_strict(len);
  }

  late final _cst_new_list_prim_u_64_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_64_strict> Function(ffi.Int32)
        >
      >('frbgen_hoodik_app_cst_new_list_prim_u_64_strict');
  late final _cst_new_list_prim_u_64_strict = _cst_new_list_prim_u_64_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_64_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_hoodik_app_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_hoodik_app_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_64_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint64> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_32_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_record_u_64_u_64 extends ffi.Struct {
  @ffi.Uint64()
  external int field0;

  @ffi.Uint64()
  external int field1;
}

final class wire_cst_list_prim_u_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_ed_25519_key_pair extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> private_pem;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_pem;
}

final class wire_cst_opaque_client_start extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> state;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;
}

final class wire_cst_opaque_login_finish extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> finalization;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> session_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> export_key;
}

final class wire_cst_opaque_register_finish extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> export_key;
}

final class wire_cst_rsa_key_pair extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> private_key_pem;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> fingerprint;
}

final class wire_cst_rsa_public_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_pem;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> fingerprint;
}

final class wire_cst_transition_signatures extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> old_signature;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> new_signature;
}

final class wire_cst_upload_complete_summary extends ffi.Struct {
  @ffi.Int64()
  external int chunks_stored;

  external ffi.Pointer<ffi.Int64> finished_upload_at;
}

final class wire_cst_wrapping_key_pair extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> private_pem;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_pem;
}
